-- MySQL Script generated by MySQL Workbench
-- 11/18/17 11:43:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mybatis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mybatis` ;

-- -----------------------------------------------------
-- Schema mybatis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mybatis` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mybatis` ;

-- -----------------------------------------------------
-- Table `user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_group` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `country` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(50) NULL,
  `language` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `location` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(50) NULL,
  `country_id` INT(10) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(10,8)NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_name` INT(10) NULL,
  `location_id` INT(10) NULL,
  `user_group_id` INT(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `session` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) NULL,
  `date_opened` DATETIME NULL,
  `date_closed` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `request` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `request` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `method` VARCHAR(10) NULL,
  `params` VARCHAR(1000) NULL,
  `session_id` INT(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;